### ISSUE TITLE
色图命名重复

### ISSUE THREAD

**Issue by PSSF23** [RimoChan/color_site#1]
有两个葡萄色诶～

**Comment by RimoChan** [comment]
那两个葡萄色的读音是不一样的，可能是日本人比较奇怪吧……

**Comment by PSSF23** [comment]
稍微查了下，[えびいろ](https://ja.wikipedia.org/wiki/%E8%91%A1%E8%90%84%E8%89%B2)（#640125）这个颜色好像也被称作“海老色”，硬要区分的可能得改成“山葡萄色”吧。真是受够日本汉字的读音了～

**Comment by RimoChan** [comment]
你居然去查了2333
